### ISSUE TITLE
No JSON example found

### ISSUE THREAD

**Issue by FrodoVDR** [mr-manuel/venus-os_dbus-mqtt-ev-charger#1]
The example in config.sample.ini for the JSON payload is not correct. Can you provide a working JSON string? That would make it much easier to use.

**Comment by mr-manuel** [comment]
You can find it in the `README.md`. See https://github.com/mr-manuel/venus-os_dbus-mqtt-ev-charger#json-structure and click on Full (with descriptions).

I will correct the config file.
