### ISSUE TITLE
[Q] /Ac/Energy/Forward total or session?

### ISSUE THREAD

**Issue by mdkeil** [mr-manuel/venus-os_dbus-mqtt-ev-charger#2]
Does the value refer to the total charging energy or to the current charging session?

**Comment by mr-manuel** [comment]
Total

**Comment by mdkeil** [comment]
thxs for your quick answer.. but I found a litte bit of inconsistency?

`/Ac/Energy/Forward         --> Write: Charged Energy (Wh)`

With your implementation the value must be set in **kWh** not in Wh, otherwise the displayed value in VRM is too high by a factor of 1000.

**Comment by mr-manuel** [comment]
Thanks, I corrected it.

**Comment by mdkeil** [comment]
PR with some more minors #3
