### ISSUE TITLE
How to get a mqtt feeedback?

### ISSUE THREAD

**Issue by JMQ1961** [mr-manuel/venus-os_dbus-mqtt-ev-charger#4]
I want to switch on /off  and the charging current of the Charging Station  via the victron system.
I do not receive a MQTT message.

is this a config problem)

have a nice day.

JM

**Comment by mr-manuel** [comment]
See https://github.com/victronenergy/dbus-flashmq

**Comment by JMQ1961** [comment]
Thank you for the quick answer.

I used a externel MQTT server.
Now i have switched to the guildin  flashMQ venus server.

But i can still see no on and off , and current commands.

I use the MQTT explorer  for test monitoring.

as i have a Keba charging station i modifiied the path from custom/ev-charger to Keba/ev-charger.

![grafik](https://github.com/mr-manuel/venus-os_dbus-mqtt-ev-charger/assets/62738715/fca4cc4b-5fd9-4702-b4ab-13ad6c7fe4fd)

**Comment by mr-manuel** [comment]
You want to see the changes that are done in Venus OS right? The topics are only one way.

The topic `Keba/ev-charger` is the receiving one for Venus OS and the sending one for your ev charger.

The topics `N/YOURVRMID/evcharger/VRMID/*` are the sending one from Venus OS and can be received by every client. The topics of Venus OS reflect the dbus. Therefore here you find the ev charger controls that change.

**Comment by JMQ1961** [comment]
First i am using OS v3.40~2 beta.

nothing is received . may be a beta problem.

![mqtt](https://github.com/mr-manuel/venus-os_dbus-mqtt-ev-charger/assets/62738715/bb3e3b48-1645-42b9-96a2-b8d7e839cc86)

the charging station is recognized. but no feedback  on of charge current
![grafik](https://github.com/mr-manuel/venus-os_dbus-mqtt-ev-charger/assets/62738715/b0aae79b-93a9-4ac5-8217-d3f58706c309)
![grafik](https://github.com/mr-manuel/venus-os_dbus-mqtt-ev-charger/assets/62738715/516d54d7-4e50-4bbd-8bbb-a737be432f2c)

**Comment by mr-manuel** [comment]
> See https://github.com/victronenergy/dbus-flashmq

You have to read this. Check the keep alive section.

**Comment by JMQ1961** [comment]
One million thanks

keep alive is the solution.


have a nice day.
