### ISSUE TITLE
EVCS load counted twice

### ISSUE THREAD

**Issue by gnissahr** [mr-manuel/venus-os_dbus-mqtt-ev-charger#5]
I have successfully managed to integrate my Alfen EV charger to the venusOS system thanks to your driver.

Since the EVCS has it's own power reading, I don't think this should be included in the AC loads as well. Technically it is an AC load, but since it is displayed seperately, I don't think it should be counted twice.

Is there any way to subtract it from the AC loads (but not from Total Consumption)?

![image](https://github.com/user-attachments/assets/3e358dab-8198-440f-b88e-9b1268730d02)

**Comment by mr-manuel** [comment]
If you set the right position, it should work.

https://github.com/mr-manuel/venus-os_dbus-mqtt-ev-charger/blob/d797b46b293c728706c1029c5e0b596ca7a5510d/dbus-mqtt-ev-charger/config.sample.ini#L27-L30

**Comment by gnissahr** [comment]
I have set it to 1, since it is on AC in, the VRM screenshot is correct.

```
; position (connected input/output) of the ev charger
; 0 = AC output
; 1 = AC input
position = 1
```
There is another option to set the position, however, here the numbers are the other way around.  Should I set this in the JSON as well?

![image](https://github.com/user-attachments/assets/308c2291-b763-4627-ab7d-97df3fea4c05)

**Comment by mr-manuel** [comment]
This is correct:

```ini
; position (connected input/output) of the ev charger
; 0 = AC input
; 1 = AC output
position = 0
```

Will update the code tomorrow

**Comment by mr-manuel** [comment]
You don't have to set it in the JSON again. The value in the `config.sample.ini` was wrong.

I updated the file now.
